#!/usr/bin/env node
// Convert the vendored robot-eye bitmaps (tools/ani_emo_eyes_src.h) into
// LVGL 9 A8 image descriptors at firmware/src/emo_eyes.h.
//
// Source format: 32x32 1-bpp frames written as `B0101....` byte literals
// (4 bytes/row, 32 rows, MSB-first) plus a `const unsigned char
// *peyes[][3][2]` table mapping mood -> {frame}{left,right}. We only need
// frame [0] per mood (matches upstream Display_Emotion.ino) plus eye0 as the
// universal blink frame.
//
// Output is A8 (alpha-only): 0xFF where a source bit is set, 0x00 otherwise.
// A8 lets emo.cpp tint the eye via image_recolor and scale it smoothly.
//
// Usage: node tools/convert_ani_emo.js

const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'ani_emo_eyes_src.h');
const OUT = path.join(__dirname, '..', 'firmware', 'src', 'emo_eyes.h');
const W = 32, H = 32;

const src = fs.readFileSync(SRC, 'utf8');

// ── Parse every `static const unsigned char PROGMEM <name>[] = { Bxxxx, ... };`
const frames = {}; // name -> Uint8Array(W*H) alpha
const frameRe = /static\s+const\s+unsigned\s+char\s+PROGMEM\s+(\w+)\s*\[\]\s*=\s*\{([^}]*)\}/g;
let m;
while ((m = frameRe.exec(src)) !== null) {
    const name = m[1];
    const bytes = m[2].match(/B[01]{8}/g);
    if (!bytes || bytes.length !== (W / 8) * H) {
        throw new Error(`frame ${name}: expected ${(W / 8) * H} bytes, got ${bytes ? bytes.length : 0}`);
    }
    const alpha = Buffer.alloc(W * H);
    for (let row = 0; row < H; row++) {
        for (let bcol = 0; bcol < W / 8; bcol++) {
            const byte = parseInt(bytes[row * (W / 8) + bcol].slice(1), 2);
            for (let bit = 0; bit < 8; bit++) {
                const set = (byte >> (7 - bit)) & 1;
                alpha[row * W + bcol * 8 + bit] = set ? 0xFF : 0x00;
            }
        }
    }
    frames[name] = alpha;
}

// ── Parse the peyes[][3][2] table, take frame 0 {left,right} per mood.
const tableMatch = src.match(/\*peyes\s*\[\]\s*\[3\]\s*\[2\]\s*=\s*\{([\s\S]*?)\};/);
if (!tableMatch) throw new Error('peyes table not found');
const rowRe = /\{\s*\{\s*(\w+)\s*,\s*(\w+)\s*\}\s*,\s*\{\s*\w+\s*,\s*\w+\s*\}\s*,\s*\{\s*\w+\s*,\s*\w+\s*\}\s*\}/g;
const moods = []; // [{left,right}]
let r;
while ((r = rowRe.exec(tableMatch[1])) !== null) {
    moods.push({ left: r[1], right: r[2] });
}
if (moods.length !== 7) throw new Error(`expected 7 moods, got ${moods.length}`);

// ── Collect the distinct frames we actually emit (frame-0 pairs + eye0 blink).
const needed = new Set(['eye0']);
moods.forEach(mo => { needed.add(mo.left); needed.add(mo.right); });
for (const n of needed) {
    if (!frames[n]) throw new Error(`needed frame ${n} not found in source`);
}

// ── Emit emo_eyes.h
let out = '';
out += '// Generated by tools/convert_ani_emo.js — DO NOT EDIT.\n';
out += '// Source: vendored tools/ani_emo_eyes_src.h\n';
out += '// 32x32 robot-eye frames as LVGL 9 A8 (alpha-only, tintable) images.\n';
out += '#pragma once\n#include <lvgl.h>\n\n';

const order = Array.from(needed).sort();
for (const name of order) {
    const a = frames[name];
    out += `static const uint8_t emo_${name}_map[] = {\n`;
    for (let row = 0; row < H; row++) {
        let line = '    ';
        for (let col = 0; col < W; col++) line += `0x${a[row * W + col].toString(16).padStart(2, '0')},`;
        out += line + '\n';
    }
    out += '};\n';
    out += `static const lv_image_dsc_t emo_img_${name} = {\n`;
    out += '    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_A8,\n';
    out += `                .flags = 0, .w = ${W}, .h = ${H}, .stride = ${W} },\n`;
    out += `    .data_size = ${W * H},\n`;
    out += `    .data = emo_${name}_map,\n`;
    out += '};\n\n';
}

out += '// Mood -> {left, right} frame-0 image (order matches emo_mood_t).\n';
out += 'static const lv_image_dsc_t* const emo_eye_frames[7][2] = {\n';
const labels = ['HAPPY', 'NEUTRAL', 'SLEEP', 'ANGRY', 'UPSET', 'SAD', 'LOVE'];
moods.forEach((mo, i) => {
    out += `    { &emo_img_${mo.left}, &emo_img_${mo.right} }, // ${labels[i]}\n`;
});
out += '};\n\n';
out += '// Universal blink frame (eye0 — flat bar).\n';
out += 'static const lv_image_dsc_t* const emo_eye_blink = &emo_img_eye0;\n';

fs.writeFileSync(OUT, out);
console.log(`Wrote ${OUT}`);
console.log(`Frames emitted: ${order.join(', ')}`);
console.log('Mood frame-0 map:');
moods.forEach((mo, i) => console.log(`  ${labels[i]}: ${mo.left} / ${mo.right}`));
